# Generated by Django 2.2.24 on 2023-09-12 18:49

import course_classification.models
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourseClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('banner', models.FileField(help_text='Banner file. px x px size', max_length=255, upload_to=course_classification.models.template_assets_path)),
                ('logo', models.FileField(help_text='Logo file. px x px size', max_length=255, upload_to=course_classification.models.template_assets_path)),
                ('sequence', models.IntegerField(verbose_name='sequence')),
                ('show_opt', models.IntegerField(choices=[(0, 'No Mostrar'), (1, 'Solo si tiene cursos'), (2, 'Siempre')], default=0, verbose_name='Mostrar')),
            ],
            options={
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CourseClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, unique=True, verbose_name='course')),
                ('MainClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_classification.MainCourseClassification', verbose_name='Clasificación Principal')),
            ],
            options={
                'ordering': ('course_id',),
            },
        ),
        migrations.CreateModel(
            name='MainCourseClassificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(help_text='Django template HTML.')),
                ('language', models.CharField(blank=True, help_text='es_419 or en', max_length=6, null=True)),
                ('main_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_classification', to='course_classification.MainCourseClassification')),
            ],
            options={
                'unique_together': {('main_classification', 'language')},
                'index_together': {('main_classification', 'language')},
            },
        ),
    ]
