# Generated by Django 2.2.24 on 2023-09-20 20:30

import course_classification.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('sequence', models.IntegerField(verbose_name='sequence')),
                ('show_opt', models.IntegerField(choices=[(0, 'No Mostrar'), (1, 'Solo si tiene cursos'), (2, 'Siempre')], default=0, verbose_name='Mostrar')),
            ],
            options={
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='courseclassification',
            name='MainClass',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='course_classification.MainCourseClassification', verbose_name='Clasificación Principal'),
        ),
        migrations.AlterField(
            model_name='maincourseclassification',
            name='banner',
            field=models.FileField(help_text='Banner file. 500 px height', max_length=255, upload_to=course_classification.models.template_assets_path),
        ),
        migrations.AlterField(
            model_name='maincourseclassification',
            name='logo',
            field=models.FileField(help_text='Logo file. 145 px height', max_length=255, upload_to=course_classification.models.template_assets_path),
        ),
        migrations.AddField(
            model_name='courseclassification',
            name='course_category',
            field=models.ManyToManyField(blank=True, to='course_classification.CourseCategory', verbose_name='Categorias'),
        ),
    ]
