# Generated by Django 2.2.24 on 2023-09-21 12:39

import course_classification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_classification', '0002_auto_20230920_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourseclassification',
            name='banner',
            field=models.FileField(blank=True, help_text='Banner file. 500 px height', max_length=255, upload_to=course_classification.models.template_assets_path),
        ),
        migrations.AlterField(
            model_name='maincourseclassification',
            name='logo',
            field=models.FileField(blank=True, help_text='Logo file. 145 px height', max_length=255, upload_to=course_classification.models.template_assets_path),
        ),
    ]
