# Generated by Django 2.2.24 on 2023-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_classification', '0003_auto_20230921_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincourseclassification',
            name='show_opt',
        ),
        migrations.AddField(
            model_name='maincourseclassification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show: True, Hide: False'),
        ),
    ]
