# Generated by Django 2.2.24 on 2023-09-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_classification', '0005_maincourseclassification_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclassification',
            name='MainClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_classification.MainCourseClassification', verbose_name='Clasificación Principal'),
        ),
    ]
