# Generated by Django 2.2.24 on 2023-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_classification', '0006_auto_20230921_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclassification',
            name='is_featured_course',
            field=models.BooleanField(default=False, help_text='if the course is featured', verbose_name='Curso Destacado'),
        ),
    ]
